services:

  local-database:
    image: mariadb:10.3
    container_name: mariadb-local-abet
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secure_root_password
      MARIADB_USER: username
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: abet_assessment_local
    ports:
      - "3307:3306"
    networks:
      - web-network
    volumes:
      # Initialize database with docker-schema.sql on first container startup
      - ./src/main/resources/docker-schema.sql:/docker-entrypoint-initdb.d/init.sql
      # Specify location on volume for data
      - mariadb_volume:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase:4.33.0
    depends_on:
      - local-database
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
      - ./src/main/resources/db/changelog:/liquibase/db/changelognp
    command: >
      /bin/bash -c "
      wget -O /liquibase/mariadb.jar https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/3.3.2/mariadb-java-client-3.3.2.jar &&
      liquibase --classpath=/liquibase/mariadb.jar --username=username --password=password --url='jdbc:mariadb://mariadb-local-abet:3306/abet_assessment_local' --changelog-file=/changelog/changelog-master.yaml update
      "
    networks:
      - web-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-local-abet:3306/abet_assessment_local
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - web-network
    depends_on:
      liquibase:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - web-network
    depends_on:
      - backend

volumes:
  mariadb_volume:

networks:
  web-network: