services:

  local-database:
    image: mariadb:10.3
    container_name: mariadb-local
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secure_root_password
      MARIADB_USER: username
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: abet_assessment_local
    ports:
      - "3306:3306"
    networks:
      - web-network
    volumes:
      # Initialize database with docker-schema.sql on first container startup
      - ./src/main/resources/docker-schema.sql:/docker-entrypoint-initdb.d/init.sql
      # Specify location on volume for data
      - mariadb_volume:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase:4.33.0
    depends_on:
      - local-database
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
      - ./src/main/resources/db/changelog:/liquibase/db/changelognp
    command: >
      /bin/bash -c "
      wget -O /liquibase/mariadb.jar https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/3.3.2/mariadb-java-client-3.3.2.jar &&
      liquibase --classpath=/liquibase/mariadb.jar --username=username --password=password --url='jdbc:mariadb://mariadb-local:3306/abet_assessment_local' --changelog-file=/changelog/changelog-master.yaml update
      "
    networks:
      - web-network

volumes:
  mariadb_volume:

networks:
  web-network: