// ===============================
// SUMMARY REPORT PARSER
// ===============================

export interface MeasureImport {
  description: string;
  metPercentage: number;
  status: string;
  recommendedActions: string[];
}

export interface CourseImport {
  courseCode: string;
  measures: MeasureImport[];
}

export interface IndicatorImport {
  number: number; // e.g., 1.1
  courses: CourseImport[];
}

export interface OutcomeImport {
  number: number; // e.g., 1
  status: string; // "Met", "Partially Met"
  indicators: IndicatorImport[];
}

export interface SummaryImport {
  generatedBy: string[];
  outcomes: OutcomeImport[];
}

// ===============================
// MAIN PARSER
// ===============================

export function parseSummaryReport(text: string): SummaryImport {
  const lines = text.split(/\r?\n/).map((l) => l.trim());

  // ===== REGEX DEFINITIONS =====
  const outcomeRegex = /^Outcome\s*\((\d+)\)\s*-\s*(.+)$/i;
  const indicatorRegex = /^\((\d+\.\d+)\)\s*-\s*(CS\s*\d+)/i;
  const measureRegex =
    /^(\d+\.\d+)-([a-z0-9]+):\s*(.*?),\s*(Met comfortably|Met|Not met|Not Met|Barely not met)[^()]*\((\d+\.?\d*)%\)/i;

  const peopleRegex = /^\d{1,2}\/\d{1,2}\/\d{2}\s*-\s*(.*)$/i;

  // ===== STATE VARIABLES =====
  const result: SummaryImport = {
    generatedBy: [],
    outcomes: []
  };

  let currentOutcome: OutcomeImport | null = null;
  let currentIndicator: IndicatorImport | null = null;
  let currentCourse: CourseImport | null = null;
  let lastMeasure: MeasureImport | null = null;
  let readingActions = false;

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (!line) {
      readingActions = false;
      continue;
    }

    // ---------- Parse "Generated By" ----------
    const p = line.match(peopleRegex);
    if (p) {
      const people = p[1]
        .split(",")
        .map((x) => x.trim())
        .filter(Boolean);
      result.generatedBy = people;
      continue;
    }

    // ---------- Recommended Actions Mode ----------
    if (readingActions && lastMeasure) {
      if (/^●\s*/.test(line)) {
        lastMeasure.recommendedActions.push(line.replace(/^●\s*/, ""));
        continue;
      } else {
        readingActions = false;
      }
    }

    // ---------- Outcome ----------
    const o = line.match(outcomeRegex);
    if (o) {
      currentOutcome = {
        number: parseInt(o[1]),
        status: o[2].trim(),
        indicators: []
      };
      result.outcomes.push(currentOutcome);
      continue;
    }

    // ---------- Indicator + Course ----------
    const ic = line.match(indicatorRegex);
    if (ic && currentOutcome) {
      const indicatorNumber = parseFloat(ic[1]);
      const courseCode = ic[2].replace(/\s+/g, "").toUpperCase(); // CS101

      // Check or create indicator
      currentIndicator =
        currentOutcome.indicators.find((i) => i.number === indicatorNumber) ||
        (() => {
          const newInd: IndicatorImport = {
            number: indicatorNumber,
            courses: []
          };
          currentOutcome!.indicators.push(newInd);
          return newInd;
        })();

      // Register the course
      currentCourse = {
        courseCode,
        measures: []
      };
      currentIndicator.courses.push(currentCourse);
      continue;
    }

    // ---------- Measure ----------
    const m = line.match(measureRegex);
    if (m && currentCourse) {
      lastMeasure = {
        description: m[3].trim(),
        status: m[4].trim(),
        metPercentage: parseFloat(m[5]),
        recommendedActions: []
      };

      currentCourse.measures.push(lastMeasure);
      continue;
    }

    // ---------- "Recommended actions:" ----------
    if (/^Recommended actions:/i.test(line)) {
      readingActions = true;
      continue;
    }
  }

  return result;
}
